require 'spec_helper'

describe Spree::Tag do

  context "validations" do
    let(:tag) { build :tag }
    it "should be valid without a description" do
      expect(tag).to be_valid
    end
    it "should have an unique name" do
      another_tag = create :tag
      expect(tag).not_to be_valid
    end

    it "should have an unique name if not match case" do
      another_tag = create :tag, name: "mondiali calcio"
      expect(tag).not_to be_valid
    end
  end

  context "permalink" do
    let(:tag) { create :tag }
    it "should be generated by name" do
      expect(tag.permalink).to eq(tag.name.to_s.to_url)
    end
  end

  context "Seo Fields" do
    let(:tag) { create :tag }
    context "Seo Slug" do
      it "should have a seo_slug" do
        expect(tag).to respond_to(:seo_slug)
      end
      it "should be the same as permalink" do
        expect(tag.seo_slug).to eq(tag.permalink)
      end
    end
    context "Seo Description" do
      it "should have a seo_description" do
        expect(tag).to respond_to(:seo_description)
      end
    end
    context "Seo Title" do
      it "should have a seo_title" do
        expect(tag).to respond_to(:seo_title)
      end
      it "should contain the name" do
        expect(tag.seo_title).to match(Regexp.new(tag.name))
      end
    end
  end
end
